# -------------------------------------------------------------------
# Toy config for both classification and regression pipelines
# -------------------------------------------------------------------

# Which high‐level ML task to run: "classification" or "regression"
task: classification

# Which stage of the pipeline
#   baseline:    just run the default models
#   feature_selection:  run sequential feature selection
#   hp_search:   run hyperparameter search
#   hp_search_fs: feature‐selection + hyperparameter search
type: baseline

# Models to include (use names exactly as defined in your config module)
# Use "all" to test every available model
models:
  - Logistic Regression
  - Random Forest

# Metrics to compute
# For classification: e.g. accuracy, roc_auc, average_precision
metrics:
  - accuracy
  - roc_auc

# Random seed
random_state: 42

# Cross‐validation parameters
cv_kwargs:
  strategy: stratified
  n_splits: 5
  shuffle: true
  random_state: 42
  n_groups: 1

# Parallel jobs
n_jobs: -1

# Only needed for feature_selection, hp_search, hp_search_fs:
n_features: 3       # number of features to select
direction: forward  # "forward" or "backward"
search_type: grid   # "grid" or "random"
n_iter: 20          # number of random search iterations
scoring: accuracy   # scoring function to use for searches
